#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE SCHEMA mymood;

    CREATE TABLE mymood.scale_options (
      id              INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      uuid            VARCHAR NOT NULL CHECK (uuid <> ''),
      name            TEXT,
      position        INT,
      emoji_code      VARCHAR,
      classification  VARCHAR CHECK (classification in ('positive', 'neutral', 'negative'))
    );

    CREATE TABLE mymood.logs (
      id                      INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      uuid                    VARCHAR NOT NULL CHECK (uuid <> ''),
      content                 TEXT NOT NULL CHECK (content <> ''),
      scale_option_selection  INT NOT NULL,
      created                 TIMESTAMP DEFAULT NOW(),
      emotion_scores          JSONB,
      CONSTRAINT fk_scale_option_selection
        FOREIGN KEY(scale_option_selection)
        REFERENCES mymood.scale_options(id)
    );

    CREATE TABLE mymood.users (
      id      INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      uuid    VARCHAR NOT NULL CHECK (uuid <> ''),
      name    VARCHAR NOT NULL,
      enabled BOOLEAN DEFAULT TRUE,
      blocked BOOLEAN DEFAULT FALSE,
      created TIMESTAMP DEFAULT NOW()
    );

    CREATE TABLE mymood.exports (
      id        INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      user_id   INT,
      requested TIMESTAMP DEFAULT NOW(),
      metadata  JSONB,
      CONSTRAINT fk_user_id
        FOREIGN KEY(user_id)
        REFERENCES mymood.users(id)
    );

    INSERT INTO mymood.scale_options
      (uuid, name, position, emoji_code, classification)
    VALUES
      ('30c9e69d-972b-4422-b84b-adf4bd944f72', 'Angry', 1, '&#128545;', 'negative'),
      ('2ba25d1a-8898-4871-a6a5-5c448dcab13d', 'Sad', 2, '&#128546;', 'negative'),
      ('e129f387-2613-4476-8181-087976cdb664', 'Neutral', 3, '&#128528;', 'neutral'),
      ('89a2dbde-de6e-4749-81fc-c8d6bec9b608', 'Happy', 4, '&#128522;', 'positive'),
      ('58d8eff3-5fb4-442b-8c78-94326c0c2333', 'Thrilled', 5, '&#128513;', 'positive');

EOSQL